language: ruby
cache: bundler
rvm: 2.6

addons:
  ssh_known_hosts: access-5000014280.ud-webspace.de
  apt:
    packages:
    - lftp

install: script/bootstrap
script: script/cibuild

branches:
  only:
  - gh-pages

deploy:
  provider: script
  script: script/deploy
  skip_cleanup: true
  on:
    branch: gh-pages
