language: ruby
cache: bundler
sudo: false
rvm: 2.5

addons:
  apt:
    packages:
    - lftp

install: script/bootstrap
script: script/cibuild

branches:
  only:
  - gh-pages

deploy:
  provider: script
  script: scripts/deploy
  on:
    branch: gh-pages