title: Kleingartenverein "Zur Hoffnung" e.V. Freital
description: Unsere Kleingartenanlage mit 130 Parzellen befindet sich im Poisental am Südhang des Windbergs.
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman
permalink: pretty
collections:
- gaerten
- gallerie